/**
 * Draws `public/og-cover.png`, the 1200x630 card Messages, Slack and a forum
 * post render in place of the link.
 *
 * This is the one asset in the repo that is generated rather than written,
 * and the one that cannot be generated by either deploy workflow: rasterising
 * an SVG needs a browser, and neither workflow installs one. So the PNG is
 * committed, and this script is how it is re-made when the page it stands for
 * changes. Run it by hand:
 *
 *     node scripts/og-cover.mjs
 *
 * Two things it leans on are present in `node_modules` without being named in
 * `package.json` — `rolldown`, which vite brings, and `playwright-core`, which
 * the browser checks bring. Neither is a runtime or a test dependency and
 * neither belongs in the manifest for the sake of a script nothing in CI
 * runs; if a future install drops one, the fix is `npx` rather than a new
 * dependency. It was `esbuild` until Vite 8, which bundles with rolldown and
 * no longer installs esbuild at all — so this is the second thing that has to
 * be re-pointed when the toolchain moves, and the failure is a clean
 * ERR_MODULE_NOT_FOUND rather than a wrong card.
 *
 * The curve on the card is the real one. `marginalRateCurve` is bundled out
 * of `src/lib` and sampled for the scenario the page opens on, so the shape
 * a reader sees in the preview is the shape they land on — and if the
 * arithmetic under it ever moves, re-running this moves the picture with it.
 * A drawn-by-hand hump would go on claiming 22.2% long after the statute
 * stopped saying so.
 */
import { build } from 'rolldown';
import { chromium } from 'playwright-core';
import { existsSync, readdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { tmpdir, homedir } from 'node:os';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PUBLIC = join(ROOT, 'public');

/* ── The arithmetic ──────────────────────────────────────────────────────── */

/**
 * `src/lib` is TypeScript and this is a plain node script, so the module has
 * to be bundled before it can be imported. Everything the card needs comes
 * from the two files the page itself reads its opening state out of.
 */
async function loadTaxModule() {
  const dir = mkdtempSync(join(tmpdir(), 'og-cover-'));
  const entry = join(dir, 'entry.ts');
  const out = join(dir, 'bundle.mjs');
  writeFileSync(
    entry,
    `export * from ${JSON.stringify(join(ROOT, 'src/lib/tax/index'))};\n` +
      `export * from ${JSON.stringify(join(ROOT, 'src/lib/scenarioUrl'))};\n`,
  );
  await build({ input: entry, output: { file: out, format: 'esm' }, platform: 'node', logLevel: 'silent' });
  const mod = await import(pathToFileURL(out).href);
  rmSync(dir, { recursive: true, force: true });
  return mod;
}

/* ── The browser ─────────────────────────────────────────────────────────── */

/**
 * `chromium.executablePath()` answers with the build playwright-core *wants*,
 * which on this machine is one that was never downloaded. What is on disk is
 * whatever the last browser install left in the cache, so the cache is what
 * gets asked — newest build first, and `CHROME_PATH` ahead of all of it.
 */
function chromiumPath() {
  if (process.env.CHROME_PATH) return process.env.CHROME_PATH;
  const cache =
    process.platform === 'darwin'
      ? join(homedir(), 'Library/Caches/ms-playwright')
      : join(homedir(), '.cache/ms-playwright');
  if (!existsSync(cache)) return null;
  const leaves = [
    'chrome-headless-shell-mac-arm64/chrome-headless-shell',
    'chrome-headless-shell-linux64/chrome-headless-shell',
    'chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing',
    'chrome-linux/chrome',
  ];
  const builds = readdirSync(cache)
    .filter((name) => /^chromium(_headless_shell)?-\d+$/.test(name))
    .sort((a, b) => Number(b.split('-').pop()) - Number(a.split('-').pop()));
  for (const dir of builds) {
    for (const leaf of leaves) {
      const candidate = join(cache, dir, leaf);
      if (existsSync(candidate)) return candidate;
    }
  }
  return null;
}

/** Rasterise one SVG string at its own size. */
async function rasterise(page, svg, { width, height, path }) {
  await page.setViewportSize({ width, height });
  await page.setContent(
    `<!doctype html><html><body style="margin:0;background:transparent">${svg}</body></html>`,
    { waitUntil: 'load' },
  );
  await page.screenshot({ path, omitBackground: true });
  console.log(`wrote ${path.replace(`${ROOT}/`, '')}  ${width}x${height}`);
}

/* ── The card ────────────────────────────────────────────────────────────── */

/** The page's own tokens. Kept in step by `the cover` in src/guards/meta.test.ts. */
const INK_BRIGHT = '#f1f1fd';
const INK_MUTED = '#9799ae';
const SURFACE = '#1a1a1b';
const EDGE = '#343940';
const EDGE_STRONG = '#4a5059';
const ACCENT = '#409dff';
const AMBER = '#f59e0b';

const FONT =
  "system-ui, -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif";

const WIDTH = 1200;
const HEIGHT = 630;

/** The plot, in card coordinates. */
const PLOT = { left: 72, right: 1128, top: 300, bottom: 540 };

const money = (n) => `$${Math.round(n / 1000)}K`;

function cover(curve) {
  const xs = curve.map((p) => p.totalIncome);
  const minX = Math.min(...xs);
  const maxX = Math.max(...xs);
  // A fixed ceiling rather than the curve's own peak: the card is one picture
  // of one scenario, and a y-axis that rescales itself would redraw the same
  // 22.2% hump at a different height every time the default moved.
  const maxY = 30;

  const x = (income) => PLOT.left + ((income - minX) / (maxX - minX)) * (PLOT.right - PLOT.left);
  const y = (rate) => PLOT.bottom - (rate / maxY) * (PLOT.bottom - PLOT.top);

  const line = curve.map((p) => `${x(p.totalIncome).toFixed(1)},${y(p.marginalRate).toFixed(1)}`);
  const path = `M${line.join('L')}`;
  const area = `${path}L${x(maxX).toFixed(1)},${PLOT.bottom}L${x(minX).toFixed(1)},${PLOT.bottom}Z`;

  // The hump, not the high ground: the curve ends up in the top bracket it
  // reaches, so the point worth labelling is the local maximum the benefit's
  // inclusion makes — the highest rate reached *before* the curve falls back.
  // With no fall-back anywhere there is no torpedo on this scenario, and the
  // global peak is the honest thing to point at instead.
  const fallBack = curve.findIndex((p, i) => i > 0 && p.marginalRate < curve[i - 1].marginalRate);
  const humpIndex =
    fallBack > 0
      ? fallBack - 1
      : curve.indexOf(curve.reduce((a, b) => (b.marginalRate > a.marginalRate ? b : a)));
  const valleyIndex =
    fallBack > 0
      ? curve.reduce((best, p, i) => (i > humpIndex && p.marginalRate < curve[best].marginalRate ? i : best), humpIndex + 1)
      : humpIndex;

  /**
   * Both features are plateaux rather than points — the 22.2% run is every
   * income at which another dollar drags 85 cents of benefit in with it — and
   * a label pinned to the run's *edge* lands on the cliff between the two,
   * which is how the hump's figure and the valley's ended up stacked in one
   * column. Pin each to the middle of its own run and the drop separates
   * them without either being moved off the thing it names.
   */
  const middleOfRun = (index) => {
    const rate = curve[index].marginalRate;
    let first = index;
    let last = index;
    while (first > 0 && curve[first - 1].marginalRate === rate) first -= 1;
    while (last < curve.length - 1 && curve[last + 1].marginalRate === rate) last += 1;
    return curve[Math.round((first + last) / 2)];
  };

  const hump = middleOfRun(humpIndex);
  const valley = middleOfRun(valleyIndex);

  const gridRates = [0, 10, 20, 30];
  const ticks = [minX, minX + (maxX - minX) / 3, minX + (2 * (maxX - minX)) / 3, maxX];

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${WIDTH}" height="${HEIGHT}" viewBox="0 0 ${WIDTH} ${HEIGHT}" font-family="${FONT}">
  <defs>
    <linearGradient id="wash" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="${ACCENT}" stop-opacity="0.28"/>
      <stop offset="100%" stop-color="${ACCENT}" stop-opacity="0.02"/>
    </linearGradient>
  </defs>

  <rect width="${WIDTH}" height="${HEIGHT}" fill="${SURFACE}"/>
  <rect width="${WIDTH}" height="4" fill="${ACCENT}"/>

  <text x="72" y="112" fill="${ACCENT}" font-size="22" font-weight="600" letter-spacing="2.4">RETIREMENT TAX TORPEDO</text>
  <text x="72" y="176" fill="${INK_BRIGHT}" font-size="54" font-weight="700">How Much Can You Take Out This Year?</text>
  <text x="72" y="224" fill="${INK_MUTED}" font-size="26">What the next dollar out of an IRA actually costs, drawn across every</text>
  <text x="72" y="260" fill="${INK_MUTED}" font-size="26">income level — with Social Security dragged into the tax base behind it.</text>

  ${gridRates
    .map(
      (rate) =>
        `<line x1="${PLOT.left}" y1="${y(rate).toFixed(1)}" x2="${PLOT.right}" y2="${y(rate).toFixed(1)}" stroke="${EDGE}" stroke-width="1"/>` +
        `<text x="${PLOT.left - 14}" y="${(y(rate) + 6).toFixed(1)}" fill="${INK_MUTED}" font-size="20" text-anchor="end">${rate}%</text>`,
    )
    .join('\n  ')}

  <path d="${area}" fill="url(#wash)"/>
  <path d="${path}" fill="none" stroke="${ACCENT}" stroke-width="5" stroke-linejoin="round" stroke-linecap="round"/>

  <line x1="${PLOT.left}" y1="${PLOT.bottom}" x2="${PLOT.right}" y2="${PLOT.bottom}" stroke="${EDGE_STRONG}" stroke-width="1"/>
  ${ticks
    .map(
      (income, i) =>
        `<text x="${x(income).toFixed(1)}" y="${PLOT.bottom + 34}" fill="${INK_MUTED}" font-size="20" text-anchor="${i === 0 ? 'start' : i === ticks.length - 1 ? 'end' : 'middle'}">${money(income)}</text>`,
    )
    .join('\n  ')}
  <text x="${PLOT.right}" y="${PLOT.bottom + 68}" fill="${INK_MUTED}" font-size="19" text-anchor="end">Total income →</text>

  <circle cx="${x(hump.totalIncome).toFixed(1)}" cy="${y(hump.marginalRate).toFixed(1)}" r="8" fill="${AMBER}"/>
  <text x="${x(hump.totalIncome).toFixed(1)}" y="${(y(hump.marginalRate) - 22).toFixed(1)}" fill="${AMBER}" font-size="30" font-weight="700" text-anchor="middle">${hump.marginalRate}%</text>
  <circle cx="${x(valley.totalIncome).toFixed(1)}" cy="${y(valley.marginalRate).toFixed(1)}" r="7" fill="${INK_MUTED}"/>
  <text x="${(x(valley.totalIncome) + 20).toFixed(1)}" y="${(y(valley.marginalRate) + 34).toFixed(1)}" fill="${INK_BRIGHT}" font-size="26" font-weight="600">back to ${valley.marginalRate}%</text>

  <text x="72" y="${PLOT.bottom + 68}" fill="${INK_MUTED}" font-size="19">ecao310.github.io/congenial-octo-spork</text>
</svg>`;
}

/** The favicon, at the one size iOS asks for as a PNG. */
function touchIcon() {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="180" height="180" viewBox="0 0 32 32">
  <rect width="32" height="32" fill="${SURFACE}"/>
  <path d="M4 25H9L12 10H16L19 18H23L27 7" fill="none" stroke="${ACCENT}" stroke-width="3" stroke-linejoin="round" stroke-linecap="round"/>
</svg>`;
}

/* ── The run ─────────────────────────────────────────────────────────────── */

const { marginalRateCurve, incomeAxisMax, defaultScenario } = await loadTaxModule();

const opening = defaultScenario();
const scenario = {
  filingStatus: opening.filingStatus,
  ssBenefit: opening.ssBenefit,
  isSenior: opening.isSenior,
  spouseIsSenior: opening.spouseIsSenior,
  muniInterest: opening.muniInterest,
  qcd: opening.qcd,
};
const curve = marginalRateCurve(scenario, { maxIncome: incomeAxisMax(scenario), step: 250 });
console.log(`curve: ${curve.length} points, ${money(curve[0].totalIncome)}–${money(curve.at(-1).totalIncome)} total income`);

const executablePath = chromiumPath();
if (!executablePath) {
  console.error('No chromium in the playwright cache. `npx playwright install chromium`, or set CHROME_PATH.');
  process.exit(1);
}

const browser = await chromium.launch({ executablePath });
const page = await browser.newPage();
await rasterise(page, cover(curve), { width: WIDTH, height: HEIGHT, path: join(PUBLIC, 'og-cover.png') });
await rasterise(page, touchIcon(), { width: 180, height: 180, path: join(PUBLIC, 'apple-touch-icon.png') });
await browser.close();
